package com.habittracker.tracker.habit;

import com.habittracker.tracker.classes.Icon;
import jakarta.persistence.*;

import java.time.LocalTime;
import java.util.ArrayList;


@Entity // This class is an entity which will occupy one row in the database
@Table // Specifies the details of the table associated with Habit. Same as class name
public class Habit {

    @Id // Sets Id as the primary key
    @SequenceGenerator( // specifies the generation strategy for primary key values.
            name = "habit_sequence",
            sequenceName = "habit_sequence",
            allocationSize = 1,
            initialValue = 0
    )
    @GeneratedValue( // Indicates th value of Id automatically generated by the specified generator
            strategy = GenerationType.SEQUENCE,
            generator = "habit_sequence"
    )
    private Long id;
    private Long userId;
    private String name;
    private String description;
    private LocalTime reminder;
    private Integer streak;

    public Habit() {

    }
    public Habit(Long id, Long userId,String name, String description, LocalTime reminder, Integer streak) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.reminder = reminder;
        this.streak = streak;
    }

    public Habit(Long userId, String name, String description, LocalTime reminder, Integer streak) {
        this.userId = userId;
        this.name = name;
        this.description = description;
        this.reminder = reminder;
        this.streak = streak;
    }

    public Long getHabitId() {
        return id;
    }

    public void setHabitId(Long id) {
        this.id = id;
    }

    public Long getUserId(){
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalTime getReminder() {
        return reminder;
    }

    public void setReminder(LocalTime reminder) {
        this.reminder = reminder;
    }
    public Integer getStreak() {
        return streak;
    }

    public void setStreak(Integer streak) {
        this.streak = streak;
    }

    @Override
    public String toString() {
        return  "UserId: " + getUserId() + "\n" +
                "Name: " + getName() + "\n" +
                "Description: " + getDescription() + "\n" +
                "Reminder: " + getReminder() + "\n" +
                "Streak: " + getStreak() + "\n"
                + "--------------------------------";
    }
}
